### ISSUE TITLE
Fullscreen breaks animation delay

### ISSUE THREAD

**Issue by mikkabouzu** [lanoxx/tilda#36] opened 2013-12-05 10:36 UTC
Animation delay setting is ignored if Tilda is used in fulscreen mode.

Tilda 1.1.8
Lubuntu 13.10

**Comment by lanoxx** [comment] 2020-02-08 21:08
This should be fixed in the master branch since both the fullscreen and the animation code have seen quite a bit of changes. The next release of Tilda version 1.5 will have these changes. If you can reproduce this issue with the latest version of tilda then feel free to open this bug.

**Closed by lanoxx** 2020-02-08 21:08 UTC
