### ISSUE TITLE
If hidden whilst fullscreen, window does not later return to orignal size

### ISSUE THREAD

**Issue by bananaoomarang** [lanoxx/tilda#225] opened 2016-02-29 18:35 UTC
### Info

Version: `1.3.2`
Desktop: KDE Plasma 5
Distro: Arch

This happens whether the pulldown animation is toggled on/off.
### Steps to Reproduce
- Show Tilda
- Toggle fullscreen on
- Hide Tilda
- Show Tilda
- Toggle fullscreen off

The window then shrinks to reveal the desktop task bar, but still fills the rest of the screen.

I think issue https://github.com/lanoxx/tilda/issues/14 is related, but opening this issue because that one is marked as solved after changes to the animation code.

**Comment by Dreadeath** [comment] 2016-03-02 03:05
Same here on Arch, Gnome.

**Comment by lanoxx** [comment] 2016-04-18 11:40
This might be specific to `kwin`, can you reproduce it with some other window manager then `kwin`?

**Comment by voidplayer** [comment] 2016-04-22 12:19
Can reproduce it
```
$ wmctrl -m
Name: Xfwm4
Class: xfwm4
PID: 13737
Window manager's "showing the desktop" mode: N/A
```

**Comment by JaikrishnaTS** [comment] 2016-06-13 22:06
I have the same issue on Ubuntu-Gnome 16.04. 
The issue is easily reproducible by following the steps of OP. 

Tested on plain Ubuntu 16.04 and the issue doesn't occur. Any clue on how to fix it?

**Comment by weyfonk** [comment] 2016-08-11 16:32
Same here on Debian testing, using i3wm.
It seems that when unfullscreening after Tilda has been pulled up then down again, the call to `gtk_window_resize` in `tilda_window_set_fullscreen` does not have any effect.

**Comment by voidplayer** [comment] 2017-01-19 15:52
Any news on this one? :)

**Comment by DustBytes** [comment] 2017-02-07 12:08
Yes affected. Checked on gnome-shell, xfce4 , openbox, plasma.
Have to open preferences and change height/width once to readjust the size

**Comment by lanoxx** [comment] 2017-02-14 16:20
A quick question, if you have animations enabled, can you also reproduce this issue? Please attach your tilda version when you reply to this question.

**Comment by voidplayer** [comment] 2017-02-14 20:47
I tried with both animation enabled and disabled. It happens the same

1.3.1-1+b1

**Comment by tedil** [comment] 2017-03-20 20:23
Also happens on GNOME Shell 3.22.3, tilda 1.3.3, arch linux.

**Comment by solacelost** [comment] 2017-05-20 15:28
Seeing same behavior in Mutter/Cinnamon on Mint Sarah. Reproduced with and without animations on 1.3.1-1. Saw a few commits over the span of this issue, anyone tracking it?

**Comment by plambros** [comment] 2017-07-13 15:00
Ubuntu Mate, tilda/xenial,now 1.3.1-1 amd64

$ wmctrl -m
Name: Metacity (Marco)
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A

Reproducible both with and without animations.

**Comment by sjaakvandenberg** [comment] 2017-08-07 11:09
Same problem here.
```
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
$ uname -a
Linux x220 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64 GNU/Linux
$ wmctrl -m
Name: Xfwm4
Class: xfwm4
PID: 816
Window manager's "showing the desktop" mode: N/A
$ tilda --version
Tilda 1.3.3
```

**Comment by philipnelson99** [comment] 2017-08-21 04:36
Still no fix I assume, but this is also an issue with another drop down terminal. [Guake has the same issue](https://github.com/Guake/guake/issues/965)

**Comment by guglez** [comment] 2017-10-19 16:20
~ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya

~ wmctrl -m
Name: Mutter (Muffin)
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A

~ tilda --version
Tilda 1.3.1


On linux-mint with Cinnamon 3.2 same behavior.

**Comment by eeshugerman** [comment] 2019-01-11 23:16
Any have a workaround for this? I still have this issue when I try to toggle by mouse like (as suggested by an earlier commenter).

**Comment by lanoxx** [comment] 2020-02-08 21:49
Commit 4c252136ec5a6393fb530f9b17a39b62f385c219 should have fixed this. This will be in tilda 1.5, please reopen if you can reproduce this with the latest version.

**Closed by lanoxx** 2020-02-08 21:49 UTC

**Comment by lanoxx** [comment] 2020-02-08 21:59
Commit 481d0af54b20f570c2929173b26adc7d1ad9b230 is also relevant to this issue.
