### ISSUE TITLE
Tilda takes a long time to toggle off

### ISSUE THREAD

**Issue by lucmp** [lanoxx/tilda#315] opened 2017-10-19 21:51 UTC
This problem started completely at random, but it is very consistent now.

The system boots, things launch at startup including Tilda, I press the key combo to toggle it on and off and it works fine, it's very quick and nimble. After about 10 seconds though, when the combo is pressed, Tilda still toggles on very fast, but takes a long time to toggle off. It always fails the first time around and I have to press the combo many times before Tilda responds and toggles off. It's nerve wrecking, and it just came up mysteriously. I have rebooted multiple times, and the problem is consistent.

It only begins after about 10 seconds so I decided to inspect the output of 'ps aux'. I ran it twice, saved the output to two files and compared. The only difference between the two is that '/lib/systemd/system$d-hostnamed' is no longer present after Tilda begins to fail to respond. It is probably unrelated.

Tilda 1.3.1-1+b2 on Debian Stretch.

**Comment by lucmp** [comment] 2017-10-19 22:23
I found old configurations in both ~/.config/tilda and old backups, and can't find a configuration that makes the problem go away. I also have tried deleting all configuration files config_0, config_1 and config_2, and still no progress.

**Comment by lucmp** [comment] 2017-10-21 15:33
Here is some new development.

I reinstalled Debian Stretch from scratch. All over again. I spent two hours installing and tweaking stuff and never had a problem with Tilda. I thought the reinstallation had fixed it. But then I replaced the new home directory with my old one, with all my personal configurations, and... the problem came back. So something in my home directory is causing it, but it's not the Tilda configuration, because I have tried deleting it and starting anew, and the problem persists. So I have no idea what could be causing it, neither do I even suspect how I can troubleshoot this.

I felt so disheartened that I looked for Quake-style console alternatives to Tilda, and I found one called 'stjerm' and it works really well, so I am kind of abandoning this issue for some indefinite time. I'll come back here and help find the cause of the problem if requested.

**Comment by lanoxx** [comment] 2017-10-29 20:14
Since I have no way to reproduce this, I will close this issue for now. If you find a way collect more information about what is happening, then please reopen the issue. One thing you could do is recompile tilda by your self, preferably the latest version from master and see if the issue still happens there. Compiling with `--enable-maintainer-flags` also enables additional debug output, which might be useful to debug the issue.

**Closed by lanoxx** 2017-10-29 20:14 UTC

**Comment by lucmp** [comment] 2017-10-29 21:22
I don't like to compile software from source. I am not a developer and compilation fails on me 95% of the time, which is very frustrating and offputting. I was hoping I would get instructions that any layman could follow and try to find out what is causing it, more in the interest of the software than mine since I've found a good alternative, but you are obviously not interested because it doesn't affect you, so whatever.
