### ISSUE TITLE
Auto-resize Height & Width Setting Checkbox

### ISSUE THREAD

**Issue by AlexAtkinson** [lanoxx/tilda#341] opened 2018-04-03 04:19 UTC
When hosting linux in a VM in a window, and then changing the VM to fullscreen, Tilda does not adjust to the new screen resolution, but instead preserves the height and width pixel settings.
Please make the standard behavior to auto-resize (maintaining the specified window size by percentage) when screen size changes are detected, and add a checkbox enabling the user to prevent auto-resize if desired, though I expect this would go unused.

**Comment by voidplayer** [comment] 2018-04-10 04:41
This seems quite an unusual behaviour. Unless the window is full screen, i dont know of any other program that resizes when you resize the vm

Do you have any example so we can look at the code?

**Comment by lanoxx** [comment] 2018-11-10 17:42
This is fixed in the https://github.com/lanoxx/tilda/tree/wip/resize branch. It would be nice if you could test it and provide some feedback on how it works. Note, this will require that you compile tilda from the git sources using the `wip/resize` branch.

In order to implement this, I had to change the way tilda stores its configured size. It now uses the relative percentage rather than the absolute size in pixels. This also required a change in the wizard, which now shows two decimal digits in the percentage spinners under the appearance tab.

If you test this please pay attention to the following things:

 1. Are your original size settings properly migrated by tilda. This should happen automatically and tilda will comment out the deprecated values for `max_width` and `max_height` from the config file and instead write new `width_percentage` and `height_percentage` options with the migrated values.
 2. Is size of the tilda window updated reliably in all cases.
 3. Does the switch from absolute values to relative values cause any unforeseen side effects.

**Comment by jojoob** [comment] 2018-11-12 09:43
As soon as I change the width and high in the preferences tilda reports "A occurred while parsing the config file." on next tilda start.

**Comment by lanoxx** [comment] 2018-11-12 18:14
Interesting. I wonder if this might be caused by a different locale setting. Can you try to replace the `,` fraction separator with a dot to see if that helps:
 
Try:

`width_percentage=85.000000`

Same for height.

**Comment by jojoob** [comment] 2018-11-13 10:08
The problem occurs event with the default config after restarting tilda. When I change the `,` to a `.` tilda reports the following error on startup:

![screenshot from 2018-11-13 11-04-56](https://user-images.githubusercontent.com/4180675/48406323-75794e80-e734-11e8-98b5-1b456097b1af.png)

**Comment by lanoxx** [comment] 2018-11-13 21:02
I pushed one more commit to output some debug values. Can you post the log output from the tilda start. 

I am wondering if tilda is unable to get the available workarea to compute its size from the available workarea and the configured relative size.

**Comment by jojoob** [comment] 2018-11-18 16:39
Tilda outputs: `/home/jojoob/.config/tilda/config_1:68: unexpected token ','`

**Comment by lanoxx** [comment] 2018-12-29 10:55
I merged the `wip/resize` branch today. This should be fixed now.

**Closed by lanoxx** 2018-12-29 10:55 UTC
