### ISSUE TITLE
Url-parsing cuts on at-sign "@"

### ISSUE THREAD

**Issue by demlak** [lanoxx/tilda#404] opened 2020-02-09 15:39 UTC
Hi,
i'm using tilda 1.5.0 and when there are urls detected, those are cut at at-sign "@"

for xample `https://www.flickr.com/photos/22047531@N03/49224861571/`
is detected as `https://www.flickr.com/photos/22047531` for clicking on it

**Comment by lanoxx** [comment] 2020-02-09 17:51
There was a change to the URL detection code, but I do not think that it caused this issue: https://github.com/lanoxx/tilda/commit/2a0f9fbbded7d0efa67cf1ef3f44b514d87eb514

Can you confirm if this worked in an older version of tilda?

**Comment by demlak** [comment] 2020-02-09 17:55
i can confirm that in 1.4.1 the behaviour is the same

**Comment by lanoxx** [comment] 2020-02-09 17:57
Then its not a regression but never the less something that should be fixed.

**Comment by demlak** [comment] 2020-02-09 17:59
thx a lot for your fast reactions.. (i was responsible for the other url parser issue taht you fixed)

**Comment by lanoxx** [comment] 2020-02-10 20:42
URL handling is really a complex matter and any solution in tilda is probably bound to have some limits, especially since URLs are evolving over time. I am considering to make this configurable via a UI option so users can tweak the Regex that is used for matching URLs. Nevertheless we should probably improve the default and add some more special cases to the regex.

The default is defined here: https://github.com/lanoxx/tilda/blob/master/src/tilda_terminal.c#L35

Feel free to make some suggestions of a better regular expression.

**Comment by demlak** [comment] 2020-02-10 22:51
since i cant speak regex, i'm totaly lost..

but well.. i think, there must be anyone else on the planet who has managed a good one? this is for sure no specialised problem.. and more wide spread?

**Closed** 2020-05-03 19:24 UTC

**Comment by lanoxx** [comment] 2020-05-13 19:02
Fixed in master by commit e4b6757364dbbf60f064f8036df96ef906251d39 and in tilda-1-5 by commit 919afad771ad815dd54875c6788d49827698bffa.

**Comment by lanoxx** [comment] 2020-05-24 21:53
I have created a stable release update for Ubuntu 20.04 focal which is currently in the proposed updates and should become available once the package moves into the updates repository.
