### ISSUE TITLE
Start tilda in fullscreen

### ISSUE THREAD

**Issue by skrat** [lanoxx/tilda#108] opened 2014-11-30 12:30 UTC
This is obvious, why isn't there a config or command line option for this? It'd save some clicking after every (re)boot.

**Comment by pik** [comment] 2015-02-15 23:08
Is this a duplicate of #32 ?

**Comment by lanoxx** [comment] 2015-06-16 10:08
Closing, its a duplicate and its already fixed in 71e1098f9a7a7680672e79592e6797b0ecb44b29

**Closed by lanoxx** 2015-06-16 10:08 UTC
