### ISSUE TITLE
Tilda won't open in specific monitors

### ISSUE THREAD

**Issue by joaov777** [lanoxx/tilda#395] opened 2019-07-23 17:17 UTC
I have a two monitor setup and I have mapped on Tilda my first terminal (accessed by F1) to open on left monitor and the second terminal (Accessed by F2) to open on the right monitor. However, the terminals will only open on the screen where the mouse is located regardless of any configuration I might have previously made.

Below, my config for both terminals alocated on each monitor. 

![image](https://user-images.githubusercontent.com/39555841/61732672-7e570100-ad54-11e9-84fd-4bb2ffc559ce.png)
![image](https://user-images.githubusercontent.com/39555841/61732687-8b73f000-ad54-11e9-88ea-76f35e26000a.png)

Thanks in advance.

**Comment by lanoxx** [comment] 2019-10-26 13:50
Which window manager and version are you using? Which desktop environment?

**Comment by lanoxx** [comment] 2019-11-01 16:54
This kind of behavior can very much depend on the window manager that is being used such as metacity, compiz, kwin, marco, xfwm4,etc. Unfortunately, there are a lot of window managers in the Linux ecosystem. Without knowing which window manager you are using this is impossible to fix.

**Comment by lanoxx** [comment] 2020-02-08 22:28
I am going to close this. Most likely this issue is caused by the window manager which decides to open tilda on a different window and in this case there is not much that tilda could do anyway.

**Closed by lanoxx** 2020-02-08 22:28 UTC
