### ISSUE TITLE
dvtm issues

### ISSUE THREAD

**Issue by richardpearl** [lanoxx/tilda#182] opened 2015-09-02 05:07 UTC
Keep up the great work on tilda! Great emulator!

Anyway, I've been occasionally encountering issues that seem to be kind of random while using dvtm. I think it is a problem with Tilda because I haven't had the problem with any other terminals.

Anyway, dvtm uses ncurses, and occasionally, Tilda makes it look crazy (like every time I'll press enter--all the text on the screen indents, when I split the terminal into two windows sometimes text will overflow to the other, the line to separate the terminals will disappear, etc.)

Is anyone else having these kind of issues?

Thanks!

**Comment by richardpearl** [comment] 2015-09-02 06:20
Could this be because I was using the "custom command" in the preferences to run dvtm? Is that incorrect?

**Comment by lanoxx** [comment] 2015-09-02 12:58
The custom command spawning function should use the default shell of your system to run the custom command. That is usually /bin/bash. I don't think this is the cause. But I am also not sure what else could be causing it. Can you maybe attach a few screenshots that demonstrate the problem.

**Comment by richardpearl** [comment] 2015-09-03 02:01
Well, since yesterday, I've just been manually typing in dvtm rather than using the custom command, and I haven't had any problems. I'll update this thread with some screenshots if something comes up.

**Comment by lanoxx** [comment] 2015-10-11 20:14
I just tried dvtm, never used it before. Its actually quite nice.

For me actually starting dvtm as a custom command works better then starting it in an already open tilda. When I open it in an already open tilda then I have problem with the transparent background, dvtm seems to override it with a nontransparent background. When I start it as a custom commend I do not have that problem.

**Comment by lanoxx** [comment] 2015-12-01 16:53
I am going to close this. If you still experience issues please let me know.

**Closed by lanoxx** 2015-12-01 16:53 UTC
