### ISSUE TITLE
when drop down keybind pressed after full screen keybind tilda resolution is changed to fullscreen

### ISSUE THREAD

**Issue by MichaelJuan** [lanoxx/tilda#297] opened 2017-07-17 10:40 UTC
When you press the full screen keybind and then press the drop down keybind, and press the drop down keybind again the window is fullscreen and no longer the resolution set in the preferences.

**Comment by sjaakvandenberg** [comment] 2017-08-10 19:54
Possible duplicate of #225.

**Comment by lanoxx** [comment] 2020-02-10 21:50
Closing as duplicate of #225, #306, #371

**Closed by lanoxx** 2020-02-10 21:50 UTC
