### ISSUE TITLE
Use <Tab> key in keybindings

### ISSUE THREAD

**Issue by danielleontiev** [lanoxx/tilda#352] opened 2018-06-04 18:12 UTC
I would like to set keybinding to `<Primary><Tab>`. When I try to do it throw settings it does not recognize `Tab` key. I did it manually in `config_0` but it sadly does not work. I've tried `<Tab>` and `Tab` in config file.

**Comment by ddska** [comment] 2019-12-27 02:37
Same here, I want to switch tabs by pressing Control+Tab, but it's not recognized in the GUI.

`nexttab_key="<Control>Tab"` in the config also does not work.

**Comment by ddska** [comment] 2019-12-27 03:13
Duplicate of https://github.com/lanoxx/tilda/issues/39

**Comment by lanoxx** [comment] 2020-02-08 21:09
Closing since its a duplicate.

**Closed by lanoxx** 2020-02-08 21:09 UTC
