### ISSUE TITLE
Links recognition is broken on Ubuntu 20.04 Tilda 1.5.0

### ISSUE THREAD

**Issue by falxcerebri** [lanoxx/tilda#414] opened 2020-04-28 12:24 UTC
I've upgraded from Ubuntu 18.10 to 20.04 and everything works fine besides links recognition. 

I can provide more details if necessary. Using Tilda 1.5.0 (from Ubuntu repo)

My Tilda config:
```
tilda_config_version="1.5.0"
# command=""
font="JetBrainsMono Nerd Font Mono 11"
key="<Primary>grave"
addtab_key="<Shift><Control>t"
fullscreen_key="F11"
toggle_transparency_key="F12"
toggle_searchbar_key="<Shift><Control>f"
closetab_key="<Shift><Control>w"
nexttab_key="<Control>Page_Down"
prevtab_key="<Control>Page_Up"
movetableft_key="<Shift><Control>Page_Up"
movetabright_key="<Shift><Control>Page_Down"
gototab_1_key="<Alt>1"
gototab_2_key="<Alt>2"
gototab_3_key="<Alt>3"
gototab_4_key="<Alt>4"
gototab_5_key="<Alt>5"
gototab_6_key="<Alt>6"
gototab_7_key="<Alt>7"
gototab_8_key="<Alt>8"
gototab_9_key="<Alt>9"
gototab_10_key="<Alt>0"
copy_key="<Shift><Control>c"
paste_key="<Shift><Control>v"
quit_key="<Shift><Control>q"
title="Dropdown Console"
background_color="white"
# working_dir=""
web_browser="x-www-browser"
increase_font_size_key="<Control>equal"
decrease_font_size_key="<Control>minus"
normalize_font_size_key="<Control>0"
# show_on_monitor=""
word_chars="-A-Za-z0-9,./?%&#:_"
lines=5000
x_pos=0
y_pos=27
tab_pos=0
expand_tabs=false
show_single_tab=false
backspace_key=0
delete_key=1
d_set_title=3
command_exit=2
command_timeout_ms=3000
scheme=3
slide_sleep_usec=2000
animation_orientation=0
timer_resolution=200
auto_hide_time=2000
on_last_terminal_exit=2
prompt_on_exit=false
palette_scheme=0
non_focus_pull_up_behaviour=0
cursor_shape=0
title_max_length=3
palette = {11822, 13364, 13878, 52428, 0, 0, 20046, 39578, 1542, 50372, 41120, 0, 13364, 25957, 42148, 30069, 20560, 31611, 1542, 38944, 39578, 54227, 55255, 53199, 21845, 22359, 21331, 61423, 10537, 10537, 35466, 58082, 13364, 64764, 59881, 20303, 29298, 40863, 53199, 44461, 32639, 43176, 13364, 58082, 58082, 61166, 61166, 60652}
scrollbar_pos=2
back_red=0
back_green=0
back_blue=0
text_red=65535
text_green=65535
text_blue=65535
cursor_red=65535
cursor_green=65535
cursor_blue=65535
width_percentage=2147483647
height_percentage=1717127924
scroll_history_infinite=false
scroll_on_output=false
notebook_border=false
scrollbar=false
grab_focus=true
above=true
notaskbar=true
blinks=true
scroll_on_key=true
bell=false
run_command=false
pinned=true
animation=true
hidden=true
set_as_desktop=false
centered_horizontally=false
centered_vertically=false
enable_transparency=true
auto_hide_on_focus_lost=false
auto_hide_on_mouse_leave=false
title_behaviour=2
inherit_working_dir=true
command_login_shell=true
start_fullscreen=false
confirm_close_tab=false
back_alpha=55705
show_title_tooltip=false
# max_width=0
# max_height=0
# image=""
# show_on_monitor_number=0
# transparency=0
# bold=false
# title_max_length_flag=false
# antialias=false
# double_buffer=false
# scroll_background=false
# use_image=false
# min_width=0
# min_height=0
```

**Comment by lanoxx** [comment] 2020-05-02 21:28
This is a duplicate of #406

**Closed by lanoxx** 2020-05-02 21:28 UTC
