### ISSUE TITLE
Tilda quits after closing preferences window

### ISSUE THREAD

**Issue by sryze** [lanoxx/tilda#364] opened 2018-09-09 05:29 UTC
If I open preferences and close them, even without changing anything, Tilda quits immediately. It outputs the following error:

```
(tilda:30781): tilda-ERROR **: 11:27:05.978: X Error: BadMatch (invalid parameter attributes)
```

Stack trace (not very helpful it seems):

```
(gdb) bt
#0  0x00007ffff64b0c41 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff64b3571 in g_log_writer_default () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff64b17de in g_log_structured_array () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff64b222e in g_log_structured_standard () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x0000555555572947 in xerror_handler (d=0x5555557ccd50, e=0x7fffffffda10) at src/xerror.c:38
#5  0x00007ffff5cf78ba in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff5cf47eb in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007ffff5cf4895 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007ffff5cf51c5 in _XEventsQueued () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007ffff5ce6d3d in XPending () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007ffff723fff1 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#11 0x00007ffff64aae51 in g_main_context_check () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff64ab3e0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff64ab7d2 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff76fd385 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x000055555556244c in main (argc=1, argv=0x7fffffffdf98) at src/tilda.c:863
```

I have also tried building from the latest code from the master branch - same result.

OS: Ubuntu 18.04 64-bit

**Comment by sryze** [comment] 2018-09-09 05:34
```
$ G_MESSAGES_DEBUG=all  ~/.local/tilda/bin/tilda
tilda.c: FUNCTION ENTERED: main: Using libvte version: 0.52.2
tilda.c: FUNCTION ENTERED: remove_stale_lock_files
tilda.c: FUNCTION ENTERED: islockfile
tilda.c: FUNCTION ENTERED: create_lock_file
tilda.c: FUNCTION ENTERED: get_instance_number
tilda.c: FUNCTION ENTERED: islockfile
tilda.c: FUNCTION ENTERED: create_lock_file
tilda.c: FUNCTION ENTERED: parse_cli
tilda.c: FUNCTION ENTERED: get_config_file_name
tilda_window.c: FUNCTION ENTERED: tilda_window_init
tilda_window.c: FUNCTION ENTERED: tilda_window_set_fullscreen
tilda_window.c: FUNCTION ENTERED: tilda_window_add_tab
tilda_terminal.c: FUNCTION ENTERED: tilda_term_init
tilda_terminal.c: FUNCTION ENTERED: tilda_term_config_defaults
tilda_terminal.c: FUNCTION ENTERED: tilda_term_adjust_font_scale
tilda_terminal.c: FUNCTION ENTERED: tilda_term_set_scrollbar_position

(tilda:30972): Vte-WARNING **: 11:33:19.100: (../../src/vtegtk.cc:1906):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
tilda_terminal.c: FUNCTION ENTERED: start_shell
tilda_terminal.c: FUNCTION ENTERED: tilda_terminal_switch_page_cb
key_grabber.c: FUNCTION ENTERED: generate_animation_positions
(tilda:30972): tilda-DEBUG: 11:33:19.111: Virtual modifier for 'caps_lock_mask' set to: GDK_LOCK_MASK
(tilda:30972): tilda-DEBUG: 11:33:19.111: Virtual modifier for 'num_lock_mask' set to: GDK_MOD2_MASK
(tilda:30972): tilda-DEBUG: 11:33:19.111: Virtual modifier for 'scroll_lock_mask' set to: 
(tilda:30972): tilda-DEBUG: 11:33:19.111: Resolved accelerator: <Primary>grave. KeySymbol: 96, Virtual Modifiers: GDK_CONTROL_MASK
(tilda:30972): tilda-DEBUG: 11:33:19.111: Binding to keycode 49
(tilda:30972): tilda-DEBUG: 11:33:19.111: Binding to real modifier mask 4 (GDK_CONTROL_MASK)
(tilda:30972): tilda-DEBUG: 11:33:19.112: Added binding. Keystring: <Primary>grave
key_grabber.c: FUNCTION ENTERED: pull
Tilda has started. Press <Primary>grave to pull down the window.
(tilda:30972): tilda-DEBUG: 11:33:20.007: Got KeyPress! keycode: 49, modifiers: 4
(tilda:30972): tilda-DEBUG: 11:33:20.007: Current event time 1688505
(tilda:30972): tilda-DEBUG: 11:33:20.007: Calling handler for '<Primary>grave'...
key_grabber.c: FUNCTION ENTERED: onKeybindingPull
key_grabber.c: FUNCTION ENTERED: pull
tilda_window.c: FUNCTION ENTERED: focus_term
key_grabber.c: FUNCTION ENTERED: tilda_window_set_active
(tilda:30972): tilda-DEBUG: 11:33:20.012: pull_down(): MOVED DOWN
tilda_window.c: FUNCTION ENTERED: mouse_enter
tilda_window.c: FUNCTION ENTERED: mouse_leave
(tilda:30972): tilda-DEBUG: 11:33:20.124: Got KeyRelease!
tilda_terminal.c: FUNCTION ENTERED: button_press_cb
tilda_terminal.c: FUNCTION ENTERED: popup_menu
tilda_window.c: FUNCTION ENTERED: mouse_leave
tilda_window.c: FUNCTION ENTERED: focus_out_event_cb
tilda_window.c: FUNCTION ENTERED: start_auto_hide_tick
tilda_terminal.c: FUNCTION ENTERED: on_popup_hide
tilda_terminal.c: FUNCTION ENTERED: menu_config_cb
wizard.c: FUNCTION ENTERED: wizard
wizard.c: FUNCTION ENTERED: find_monitor_number
wizard.c: FUNCTION ENTERED: initialize_geometry_spinners
wizard.c: FUNCTION ENTERED: find_monitor_number
wizard.c: FUNCTION ENTERED: percentage_dimension
wizard.c: FUNCTION ENTERED: percentage_dimension
(tilda:30972): tilda-DEBUG: 11:33:22.077: Removing grab for '<Primary>grave'
tilda_window.c: FUNCTION ENTERED: mouse_leave
tilda_window.c: FUNCTION ENTERED: mouse_enter
tilda_window.c: FUNCTION ENTERED: mouse_enter
tilda_window.c: FUNCTION ENTERED: mouse_leave
tilda_window.c: FUNCTION ENTERED: focus_out_event_cb
tilda_window.c: FUNCTION ENTERED: start_auto_hide_tick
wizard.c: FUNCTION ENTERED: wizard_close_dialog
(tilda:30972): tilda-DEBUG: 11:33:23.013: Resolved accelerator: <Primary>grave. KeySymbol: 96, Virtual Modifiers: GDK_CONTROL_MASK
(tilda:30972): tilda-DEBUG: 11:33:23.013: Binding to keycode 49
(tilda:30972): tilda-DEBUG: 11:33:23.013: Binding to real modifier mask 4 (GDK_CONTROL_MASK)
(tilda:30972): tilda-DEBUG: 11:33:23.013: Added binding. Keystring: <Primary>grave
configsys.c: FUNCTION ENTERED: config_write
tilda_window.c: FUNCTION ENTERED: focus_out_event_cb
tilda_window.c: FUNCTION ENTERED: start_auto_hide_tick
key_grabber.c: FUNCTION ENTERED: pull
(tilda:30972): tilda-DEBUG: 11:33:23.061: pull_up(): MOVED UP
tilda_window.c: FUNCTION ENTERED: focus_out_event_cb
tilda_window.c: FUNCTION ENTERED: start_auto_hide_tick
key_grabber.c: FUNCTION ENTERED: pull
tilda_window.c: FUNCTION ENTERED: mouse_leave
xerror.c: FUNCTION ENTERED: xerror_handler

(tilda:30972): tilda-ERROR **: 11:33:23.070: X Error: BadMatch (invalid parameter attributes)
Trace/breakpoint trap

```

**Comment by lanoxx** [comment] 2020-01-18 16:57
I notice that the auto hide feature is active. I am wondering if it might have anything to do with this. You could try to disable auto hide and see if that improves the situation.

**Comment by lanoxx** [comment] 2020-02-08 22:16
I am going to close this, because I cannot reproduce it with the latest version and there have been some changes that could have fixed this. If you can still reproduce this with the latest version in master or Tilda 1.5 which will be released soon, then please reopen this.

**Closed by lanoxx** 2020-02-08 22:16 UTC
