### ISSUE TITLE
tilda stubles over ps command options on busybox distro 

### ISSUE THREAD

**Issue by cypa** [lanoxx/tilda#313] opened 2017-10-12 06:33 UTC
in fact, busybox's ps has only one option which is no "-C", so when tilda tries "ps -C tilda" on startup it get error
should we use "ps | grep tilda" instead of ps -C?

**Comment by cypa** [comment] 2017-10-12 06:49
or, maybe pgrep?

**Comment by lanoxx** [comment] 2017-10-29 20:49
Duplicate of #282

**Closed by lanoxx** 2017-10-29 20:49 UTC
