### ISSUE TITLE
Does not pull down when focus on the desktop no a window  - Ubuntu 21.04

### ISSUE THREAD

**Issue by micail** [lanoxx/tilda#462] opened 2021-06-05 05:57 UTC
Great app thank you for your contribution. We appreciate it!

I have an issue with Tilda on Ubuntu 21.04 GNOME 3.38.5.

Steps to reproduce:
1. Install Tilda form Snap
2. Launch Tilda
3. Click by mouse on Desktop area to loose focus on any window
4. Press F1 to toggle Tilda

Expected:
Tilda will toggle

Result:
Tilda did not toggle

Then click on any window to focus on it, press F1 and Tilda toggles.

**Comment by lanoxx** [comment] 2021-06-05 13:50
Probably a duplicate of #407

**Closed by lanoxx** 2021-06-05 13:50 UTC

**Comment by lanoxx** [comment] 2021-06-05 13:51
If you use wayland you will need to compile tilda by your self until the next version of tilda is released. I try to make sure it gets into Ubuntu 21.10.

**Comment by klausi** [comment] 2021-07-25 19:19
Workaround on Ubuntu 21.04: switch to X11 instead of wayland as display server protocol.

Edit `/etc/gdm3/custom.conf` and uncomment `WaylandEnable=false`. Restart Ubuntu and then you should be using X11 and the Tilda toggle works again!

**Comment by pagesix1536** [comment] 2024-06-23 01:56
Chiming in... 3 years later. I just installed Fedora 40 with Gnome 46 on Wayland. Installed Tilda from the stock repos. tilda-2.0.0-1.fc40.x86_64
This issue still exists. You cannot pull down the Tilda window if the desktop, Terminal, File browser, or most any other window has focus.  Seems to pull down fine if I have Brave browser in focus though. Weird. I don't know what kind of limitations Wayland/Gnome has placed on re-mapping keys, but it broke many apps for years. Guake completely is broken too unless you resort to some kinda Gnome keyboard binding to a Python script that initiates a pulldown.
