### ISSUE TITLE
Segmentation fault when custom command is set

### ISSUE THREAD

**Issue by elig0n** [lanoxx/tilda#504] opened 2023-06-11 22:37 UTC
whether empty or not, setting any custom command (with/without login shell option checked) shows this crash:

```
(tilda:822217): VTE-CRITICAL **: 16:03:19.525: void vte_pty_spawn_with_fds_async(VtePty*, const char*, const char* const*, const char* const*, const int*, int, const int*, int, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, int, GCancellable*, GAsyncReadyCallback, gpointer): assertion 'envv == nullptr || _vte_pty_check_envv(envv)' failed
[1]    822217 segmentation fault (core dumped)  tilda              
```

tilda 1.5.4 on Manjaro Linux.

**Comment by lanoxx** [comment] 2023-11-12 16:12
Thanks, any chance you could attach a debugger like `gdb` and submit a `backtrace`?

**Comment by lanoxx** [comment] 2023-11-12 20:00
While there was one change in 1.5.4 related to command spawning, which can found in commit d377fbba4d7706e96d9872c7c3b582089eda558b, I don't think that would have caused a regression, or we would have probably seen more reports.

**Comment by lanoxx** [comment] 2023-11-12 20:22
On second thought it looks like you are observing an issue which was fixed by this #481 and commit 51a980a55ad6d750daa21d43a66d44577dad277b, 

A quick search through the git history (via `git log -L 530,540:../src/tilda_terminal.c`) shows that this bug was introduced by me in commit 42139b7ec41d7fa168d7beff54a1a7b3bffccc79 (in 2015). My apologies for this mistake.

I have cherry-picked this to the `tilda-1-5` branch and tagged a 1.5.5 release in git. I am not sure how this can find its way into Manjaro Linux.

**Comment by lanoxx** [comment] 2023-11-12 20:22
Relevant commit on tilda-1-5 branch is: d09139e65f69ce5a3634458b187839692ee10716

**Comment by lanoxx** [comment] 2023-11-12 20:26
If you can still reproduce this with in the mentioned fix, then please reopen this issue.

**Closed by lanoxx** 2023-11-12 20:26 UTC
