### ISSUE TITLE
tilda fullscreen toggle does not return to original size

### ISSUE THREAD

**Issue by stumper932** [lanoxx/tilda#371] opened 2018-10-19 09:05 UTC
**Expected behaviour**
Return from fullscreen to size set in preferences under height width

**Actual behaviour**
Return from fullscreen to default screen size before set in preferences (?)

**Steps to reproduce the behaviour**
(F12 Pull Down Terminal)
(F11 Toggle Full Screen)
F12 F11 F12 F12 F11

**Package version**
tilda/bionic,now 1.4.1-2 amd64

**Linux Distribution**
ubuntu-mate 18.04.1 lts

**Comment by stumper932** [comment] 2018-10-26 17:16
Updated original comment after i found out how to reproduce the behaviour.
Attached video: [tilda_screensize_bug.mkv.zip](https://github.com/lanoxx/tilda/files/2520147/tilda_screensize_bug.mkv.zip)

**Comment by stumper932** [comment] 2018-10-26 19:12
This could be a possible duplicate of #225 and #297

**Comment by thiswillbeyourgithub** [comment] 2019-01-22 20:12
I have the exact same issue on Ubuntu 18.04 LTS gnome :/

**Comment by stumper932** [comment] 2019-01-24 13:58
Workaround: right-mouse click -> preferences -> appearance tab -> increase height or width -> decrease height or width.

**Comment by thiswillbeyourgithub** [comment] 2019-01-24 14:14
Thanks ! I actually ticked "expand tabs" and it sems to fix it. Thanks to you !

**Comment by stumper932** [comment] 2019-01-30 16:20
Yeah, you have to do this every time  =/ .. maybe we should throw some $ to the developer to speed up the process.

**Comment by thiswillbeyourgithub** [comment] 2019-01-30 18:36
I still prefer to press the fullscreen shortcut like mad than to do all your clicky things.

Do you know how we could send monizz to the developper ?

**Comment by nshell32** [comment] 2019-03-23 08:46
Maybe the problem is in normal window size restoring after unset full screen. When I set fullscreen, then pressed Alt and left mouse button, nothing has happened. But when I tried to unset fullscreen and pressed Alt + left mouse button the window started to drag with cursor that didn't on fullscreen. Therefore, the problem could be in normal window size height and width restoring.

**Comment by makemegit** [comment] 2019-03-25 09:10
I found out that if you switch to compiz, everything works fine. I am on Ubuntu Mate 16.04 and 18.04, and i think there is some incompatibility with the window manager.

**Comment by solacelost** [comment] 2019-08-23 10:48
There have been a lot of updates since I made this PR but supposedly it's still working for people today:
https://github.com/lanoxx/tilda/pull/365
Let me know if the patch works for you.

**Comment by lanoxx** [comment] 2019-10-31 19:51
I can reproduce this with the **marco** window manager of the mate desktop, but not with the **metacity** window manager. When the error occurs then marco prints:

> Window manager warning: Treating resize request of legacy application 0x3200007 (~/Document) as a fullscreen request

With metacity the window just returns to the expected size. Could you tell me if using metacity fixes the problem for you? Just run `metacity --replace &` on a shell and try to reproduce the problem.

**Comment by lanoxx** [comment] 2020-02-10 21:51
There have been changes to the fullscreen code in 4c252136ec5a6393fb530f9b17a39b62f385c219 

Closing as duplicate of #225, #306, #371.

**Closed by lanoxx** 2020-02-10 21:51 UTC
